stages:
  - deploy

deploy-dev:
  stage: deploy
  tags:
    - dev
  only:
    - develop
  script:
    - ls -la README.md || echo "README.md not found"
    - sudo cp README.md /var/www/ || echo "Failed to copy README.md"
    - ls -la /var/www/README.md || echo "README.md not found in destination"

deploy-prod:
  stage: deploy
  tags:
    - prod
  only:
    - main
  script:
    - ls -la README.md || echo "README.md not found"
    - sudo cp README.md /var/www/ || echo "Failed to copy README.md"
    - ls -la /var/www/README.md || echo "README.md not found in destination"