stages:
  - deploy

deploy-dev:
  stage: deploy
  tags:
    - dev
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      when: always
    - when: never
  script:
    - pwd
    - ls -la
    - sudo rm -rf /var/www/*
    - sudo cp -r ./* /var/www/
    - sudo ls -la /var/www/

deploy-prod:
  stage: deploy
  tags:
    - prod
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - when: never
  script:
    - pwd
    - ls -la
    - sudo rm -rf /var/www/*
    - sudo cp -r ./* /var/www/
    - sudo ls -la /var/www/