stages:
  - deploy

deploy-dev:
  stage: deploy
  tags:
    - dev
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      when: always
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
      when: always
    - when: never
  script:
    - pwd
    - ls -la
    - mkdir -p /srv/botherless-vc/library
    - rm -rf /srv/botherless-vc/library/*
    - cp -r ./* /srv/botherless-vc/library/
    - ls -la /srv/botherless-vc/library/

deploy-prod:
  stage: deploy
  tags:
    - prod
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: manual
    - when: never
  script:
    - pwd
    - ls -la
    - mkdir -p /srv/botherless-vc/library
    - rm -rf /srv/botherless-vc/library/*
    - cp -r ./* /srv/botherless-vc/library/
    - ls -la /srv/botherless-vc/library/