stages:
  - deploy

deploy-dev:
  stage: deploy
  tags:
    - dev
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      when: always
    - when: never
  script:
    - ls -la README.md || echo "README.md not found"
    - sudo cp README.md /var/www/ || echo "Failed to copy README.md"
    - ls -la /var/www/README.md || echo "README.md not found in destination"

deploy-prod:
  stage: deploy
  tags:
    - prod
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - when: never
  script:
    - ls -la README.md || echo "README.md not found"
    - sudo cp README.md /var/www/ || echo "Failed to copy README.md"
    - ls -la /var/www/README.md || echo "README.md not found in destination"